export enum ENUM_VERIFICATION_STATUS {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  ACCEPTED = 'ACCEPTED',
}
export enum ENUM_VERIFICATION_PURPOSE {
  VERIFICATION_EMAIL = 'VERIFICATION_EMAIL',
  INVITATION = 'INVITATION',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  INVITATION_FOR_EXISTED_USER = 'INVITATION_FOR_EXISTED_USER',
}
