export enum ENUM_PERMISSION_TYPE {
  PAGE = 'PAGE',
  SUPER_ADMIN = 'SUPER_ADMIN',
  AGENCY = 'AGENCY',
  AGENCY_ADMIN = 'AGENCY_ADMIN',
  TALENT_MANAGER = 'TALENT_MANAGER',
  USER_ADMIN = 'USER_ADMIN',
}
export enum ENUM_PERMISSION_ACTION {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  READ = 'READ',
  MANAGE = 'MANAGE',
}
