export enum ENUM_VIDEO_LINK_TYPE {
  EMBEDDED = 'EMBEDDED',
  IFRAME = 'IFRAME',
  LINK = 'LINK',
}
export enum ENUM_DEEZER_THEME_TYPE {
  DARK = 'DARK',
  AVTO = 'AVTO',
  LIGHT = 'LIGHT',
}
export enum ENUM_BOOMPLAY_SIZES_TYPE {
  DEFAULT = 'DEFAULT',
  DESKTOP = 'DESKTOP',
  MOBILE = 'MOBILE',
}
export enum ENUM_WHATSAPP_ACCOUNT_TYPE {
  LINK = 'LINK',
  CHANNEL_LINK = 'CHANNEL_LINK',
}
